### PR TITLE
Update to 0.12.23

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Just noticed #50 - not sure why that didn't work as the diff seems the same. I guess kicking the CI on that PR would also have done the job.

<table>
<tr><th>PR #51</th><th>PR #50</th></tr>
<tr>
<td valign="top">

```patch
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index ac5961c..404589e 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,5 +1,5 @@
 {% set goname = "github.com/hashicorp/terraform" %}
-{% set version = "0.12.21" %}
+{% set version = "0.12.23" %}
 
 {% set name = goname.split('/')[-1] %}
 {% set pkg_src = ('src/'+goname).replace("/",os.sep) %}
@@ -13,7 +13,7 @@ source:
   # for the git sha&tag to determine its version
   - folder: {{ pkg_src }}
     url: https://{{ goname }}/archive/v{{ version }}.tar.gz
-    sha256: 313f1fd527d9c2688c895e31be6cb43d817e01b4cf38511a413b26f4a602f44e
+    sha256: fad34a55e4643313fe50168472e39c9468b7a4a37f8e81d9507adee210ea8e4b
 
 build:
   number: 0
@@ -46,3 +46,4 @@ extra:
   recipe-maintainers:
     - sodre
     - mariusvniekerk
+    - dhirschfeld
```
</td>
<td valign="top">

```patch
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index ac5961c..18c3912 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,5 +1,5 @@
 {% set goname = "github.com/hashicorp/terraform" %}
-{% set version = "0.12.21" %}
+{% set version = "0.12.23" %}
 
 {% set name = goname.split('/')[-1] %}
 {% set pkg_src = ('src/'+goname).replace("/",os.sep) %}
@@ -13,7 +13,7 @@ source:
   # for the git sha&tag to determine its version
   - folder: {{ pkg_src }}
     url: https://{{ goname }}/archive/v{{ version }}.tar.gz
-    sha256: 313f1fd527d9c2688c895e31be6cb43d817e01b4cf38511a413b26f4a602f44e
+    sha256: fad34a55e4643313fe50168472e39c9468b7a4a37f8e81d9507adee210ea8e4b
 
 build:
   number: 0
@@ -34,7 +34,7 @@ test:
 about:
   home: https://www.terraform.io
   license: MPL 2.0
-  summary: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently. 
+  summary: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
   description: |
     Terraform is a tool for building, changing, and versioning infrastructure safely and 
     efficiently. Terraform can manage existing and popular service providers as well as custom in-house 
```
</td>
</tr>
</table>

**Comment by dhirschfeld** [comment]
Ping @conda-forge/terraform!

**Comment by dhirschfeld** [comment]
It looks like we may have a heisenbug 😬 

This PR worked but the master merge failed:
https://github.com/conda-forge/terraform-feedstock/runs/497318573
```
build github.com/hashicorp/terraform:
cannot load github.com/Azure/azure-sdk-for-go/profiles/2017-03-09/resources/mgmt/resources:
rename
  D:\bld\terraform_1583830324914\work\pkg\mod\github.com\!azure\azure-sdk-for-go@v36.2.0+incompatible.tmp-794695895
  D:\bld\terraform_1583830324914\work\pkg\mod\github.com\!azure\azure-sdk-for-go@v36.2.0+incompatible:
Access is denied.
```
I'm not sure why :(

**Comment by dhirschfeld** [comment]
@xhochy I don't think I have permissions to restart the build are you able to kick the CI on master for me?

If that fails I'll try to debug/repro in a PR...

**Comment by xhochy** [comment]
> @xhochy I don't think I have permissions to restart the build are you able to kick the CI on master for me?
> 
> If that fails I'll try to debug/repro in a PR...

You can do empty commits on master for this.

**Pull request merged**
